### ISSUE TITLE
Leverage the vfeed classes

### ISSUE THREAD

**Issue by toolswatch** [menkhus/falco#5]
Hi there,

Very cool project and happy that you are relying on vFeed.

I checked your code and noticed that you are re-writing some queries that already exists. In fact, you can leverage vfeed class and import functions you need.

See doc here >> https://github.com/toolswatch/vFeed/wiki/%5B2%5D-Usage

And a sample how to call vfeed class from your python script >> https://github.com/toolswatch/vFeed/blob/master/vfeed_calls_samples.py

Anyways; i will try your tool. It sounds nice ;)

@toolswatch

**Comment by menkhus** [comment]
NJ,

Thanks a bunch for your kind and constructive comments. I looked at your
api's after I finished falco v0.4, and thought I really should have used
that code :-)

I want to package vfeed as a dependency of falco, but want to make sure
that really makes sense. Do you pan to put it in pip? I want to use the
update feature in vfeed, and then try some of the other features. After I
read your code, I realized I need to refactor this for Pep8 and code as
documentation. Keep up the great work.

The biggest feedback I have had from falco is that it needs some other type
of output format... HTML, JSON, CSV, so I plan to refactor the code to
provide those features instead of the simple print output.

Mark

Mark Menkhus,
Colorado Springs, Colorado , USA
KC0FNS

**Comment by menkhus** [comment]
version 0.5.2: I updated the falco code to pull in the vfeed features to loading and updating the database.  Looking forward to using more API features.

/Mark
